using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using Ethereal.Attributes;
using Ethereal.Utils;
using HarmonyLib;
using Newtonsoft.Json;
using UnityEngine;

namespace Ethereal.API;

[Deferrable]
public static partial class Localisation
{
    /// <summary>
    /// A language's data as stored in JSON.
    /// </summary>
    [Serializable]
    private class Language()
    {
        public string Name { get; set; } = "Custom Language";

        /// <summary>
        /// The language code used for formatting numbers and such.
        /// </summary>
        public string Code { get; set; } = "en-US";

        /// <summary>
        /// The version of the game this data was made for.
        /// </summary>
        public string GameVersion { get; set; } = "0.0.0.0";

        /// <summary>
        /// Addons are loaded after other localisations files.<para/>
        /// They can be used to add localisations to another language (custom or native).
        /// </summary>
        public bool Addon { get; set; } = false;

        public Dictionary<int, string> Localisations { get; set; } = [];
    }

    /// <summary>
    /// Localisation data for custom languages.
    /// </summary>
    /// <param name="id"></param>
    /// <param name="data"></param>
    internal class CustomLocaleData(int id, Dictionary<ELanguage, string> data)
    {
        public int Id { get; init; } = id;

        public Dictionary<ELanguage, string> Data { get; set; } = data;
    }

    /// <summary>
    /// Contains the name of all native and custom languages.
    /// </summary>
    private static readonly List<string> AllLanguageNames =
    [
        .. Enum.GetValues(typeof(ELanguage)).Cast<ELanguage>().Select(Loca.GetLanguageString),
    ];

    internal static readonly Dictionary<ELanguage, string> CustomLanguages = [];

    internal static readonly Dictionary<string, CustomLocaleData> CustomLocalisations = [];

    private static readonly string LocalesPath = Path.Join(Plugin.EtherealPath, "Locales");

    private const string TemplateName = "template.json";

    private const string TemplateWarning =
        "Do NOT edit this file directly!!! Make a copy first!!! It will get replaced every game update.";

    /// <summary>
    /// Mark the API as ready and run all deferred methods.
    /// </summary>
    internal static void SetReady()
    {
        GenerateTemplate();
        LoadLanguages();

        API.SetReady();
    }

    /// <summary>
    /// Add new localisation to the game's data.
    /// </summary>
    /// <param name="entry"></param>
    [Deferrable]
    private static void AddLocalisedText_Impl(LocalisationData.LocalisationDataEntry entry)
    {
        // Already translated
        // Need to return in case multiple mods add the same `StringContent` to localise
        if (LocalisationData.Instance.LocaEntries.ContainsKey(entry.StringContent))
            return;

        KeyValuePair<string, LocalisationData.LocalisationDataEntry> pair =
            LocalisationData.Instance.LocaEntries.FirstOrDefault(x => x.Value.ID == entry.ID);

        // Update text
        if (pair.Value != null)
        {
            if (!string.IsNullOrEmpty(entry.StringContentEnglish))
                pair.Value.StringContentEnglish = entry.StringContentEnglish;

            if (!string.IsNullOrEmpty(entry.StringContentGerman))
                pair.Value.StringContentGerman = entry.StringContentGerman;

            if (!string.IsNullOrEmpty(entry.StringContentSpanish))
                pair.Value.StringContentSpanish = entry.StringContentSpanish;

            if (!string.IsNullOrEmpty(entry.StringContentPortuguese))
                pair.Value.StringContentPortuguese = entry.StringContentPortuguese;

            if (!string.IsNullOrEmpty(entry.StringContentFrench))
                pair.Value.StringContentFrench = entry.StringContentFrench;

            if (!string.IsNullOrEmpty(entry.StringContentItalian))
                pair.Value.StringContentItalian = entry.StringContentItalian;

            if (!string.IsNullOrEmpty(entry.StringContentRussian))
                pair.Value.StringContentRussian = entry.StringContentRussian;

            if (!string.IsNullOrEmpty(entry.StringContentJapanese))
                pair.Value.StringContentJapanese = entry.StringContentJapanese;

            if (!string.IsNullOrEmpty(entry.StringContentSimplifiedChinese))
                pair.Value.StringContentSimplifiedChinese = entry.StringContentSimplifiedChinese;

            // Update the dictionary
            if (pair.Key != entry.StringContent)
            {
                pair.Value.StringContent = entry.StringContent;
                LocalisationData.Instance.LocaEntries.Remove(pair.Key);
                LocalisationData.Instance.LocaEntries.Add(entry.StringContent, pair.Value);

                // Update custom languages translation keys
                if (CustomLocalisations.ContainsKey(pair.Key))
                {
                    CustomLocalisations.Add(entry.StringContent, new(entry.ID, []));

                    foreach (
                        (ELanguage langId, string original) in CustomLocalisations[pair.Key].Data
                    )
                    {
                        CustomLocalisations[entry.StringContent].Data.Add(langId, original);
                    }

                    CustomLocalisations.Remove(pair.Key);
                }
            }
        }
        // Add text
        else
            LocalisationData.Instance.LocaEntries.Add(entry.StringContent, entry);
    }

    /// <summary>
    /// Add new localisation to the game's data, with translations for the provided custom languages.
    /// </summary>
    /// <param name="entry"></param>
    /// <param name="customLanguageEntries"></param>
    [Deferrable]
    private static void AddLocalisedText_Impl(
        LocalisationData.LocalisationDataEntry entry,
        Dictionary<string, string> customLanguageEntries
    )
    {
        AddLocalisedText(entry);

        foreach ((string langName, string text) in customLanguageEntries)
        {
            KeyValuePair<ELanguage, string> lang = CustomLanguages.FirstOrDefault(x =>
                x.Value == langName
            );

            // Language not found found
            if (lang.Value == null)
                continue;

            // Update text
            if (
                CustomLocalisations.TryGetValue(
                    entry.StringContent,
                    out CustomLocaleData localisation
                )
            )
                localisation.Data[lang.Key] = text;
            // Add text
            else
                CustomLocalisations.Add(
                    entry.StringContent,
                    new(entry.ID, new() { { lang.Key, text } })
                );
        }
    }

    /// <summary>
    /// Load languages files from the Ethereal directory.
    /// </summary>
    private static void LoadLanguages()
    {
        List<Language> languageList = [];

        foreach (FileInfo file in new DirectoryInfo(LocalesPath).EnumerateFiles())
        {
            if (file.Name == TemplateName)
                continue;

            string json = file.OpenText().ReadToEnd();

            if (JsonConvert.DeserializeObject<Language>(json) is not Language language)
                continue;

            // Remove the "don't edit this file" warning from the template
            //   in case a modder forgot to remove it
            language.Localisations.Remove(-1);
            languageList.Add(language);
        }

        foreach (Language language in languageList.OrderBy(x => x.Addon))
        {
            Log.API.LogInfo($"Loaded locale: {language.Name}{(language.Addon ? " (Addon)" : "")}");

            if (AllLanguageNames.Contains(language.Name))
                UpdateLanguage(language);
            else
                CreateLanguage(language);
        }
    }

    /// <summary>
    /// Create a new language based on a JSON file's data.
    /// </summary>
    /// <param name="language"></param>
    private static void CreateLanguage(Language language)
    {
        List<ELanguage> availableLanguages =
            (List<ELanguage>)
                AccessTools
                    .Field(typeof(LocalisationData), "availableLanguages")
                    .GetValue(LocalisationData.Instance);

        ELanguage langId =
            Enum.GetValues(typeof(ELanguage)).Cast<ELanguage>().Max() + 1 + CustomLanguages.Count;

        availableLanguages.Add(langId);
        AllLanguageNames.Add(language.Name);
        CustomLanguages.Add(langId, language.Name);

        foreach ((int locaId, string text) in language.Localisations)
        {
            if (
                !LocalisationData.Instance.LocaEntries.TryGetKey(
                    x => x.Value?.ID == locaId,
                    out string original
                )
            )
            {
                LocalisationData.Instance.LocaEntries.Add(
                    text,
                    new()
                    {
                        ID = locaId,
                        StringContent = text,
                        StringContentEnglish = text,
                    }
                );

                original = text;
            }

            // Already localised in another custom language
            if (CustomLocalisations.TryGetValue(original, out CustomLocaleData localisation1))
                localisation1.Data[langId] = text;
            // Not localised in any custom language yet
            else
                CustomLocalisations.Add(original, new(locaId, new() { { langId, text } }));
        }

        // Add culture format
        Dictionary<ELanguage, CultureInfo> CultureInfos =
            (Dictionary<ELanguage, CultureInfo>)
                AccessTools.Field(typeof(global::Utils), "CultureInfos").GetValue(null);

        if (CultureInfos == null)
        {
            CultureInfos = new Dictionary<ELanguage, CultureInfo>
            {
                { ELanguage.English, CultureInfo.CreateSpecificCulture("en-US") },
                { ELanguage.Chinese, CultureInfo.CreateSpecificCulture("zh-CN") },
                { ELanguage.French, CultureInfo.CreateSpecificCulture("fr-FR") },
                { ELanguage.German, CultureInfo.CreateSpecificCulture("de-DE") },
                { ELanguage.Italian, CultureInfo.CreateSpecificCulture("it-IT") },
                { ELanguage.Russian, CultureInfo.CreateSpecificCulture("ru-RU") },
                { ELanguage.Spanish, CultureInfo.CreateSpecificCulture("es-ES") },
                { ELanguage.Japanese, CultureInfo.CreateSpecificCulture("ja-JP") },
            };

            AccessTools.Field(typeof(global::Utils), "CultureInfos").SetValue(null, CultureInfos);
        }

        try
        {
            CultureInfos.Add(langId, CultureInfo.CreateSpecificCulture(language.Code));
        }
        catch (CultureNotFoundException)
        {
            CultureInfos.Add(langId, CultureInfo.CreateSpecificCulture("en-US"));
        }
    }

    /// <summary>
    /// Update an existing language's localisations based on a JSON file's data.
    /// </summary>
    /// <param name="language"></param>
    private static void UpdateLanguage(Language language)
    {
        foreach ((int locaId, string text) in language.Localisations)
        {
            (string original, LocalisationData.LocalisationDataEntry? entry) =
                LocalisationData.Instance.LocaEntries.FirstOrDefault(x => x.Value.ID == locaId);

            // Create native localisation if it doesn't exist
            if (entry == null)
            {
                original = text;
                entry = new()
                {
                    ID = locaId,
                    StringContent = text,
                    StringContentEnglish = text,
                };

                LocalisationData.Instance.LocaEntries.Add(text, entry);
            }

            // Native languages
            if (language.Name == Loca.GetLanguageString(ELanguage.English))
                entry.StringContentEnglish = text;
            else if (language.Name == Loca.GetLanguageString(ELanguage.German))
                entry.StringContentGerman = text;
            else if (language.Name == Loca.GetLanguageString(ELanguage.Spanish))
                entry.StringContentSpanish = text;
            else if (language.Name == Loca.GetLanguageString(ELanguage.Portuguese))
                entry.StringContentPortuguese = text;
            else if (language.Name == Loca.GetLanguageString(ELanguage.French))
                entry.StringContentFrench = text;
            else if (language.Name == Loca.GetLanguageString(ELanguage.Italian))
                entry.StringContentItalian = text;
            else if (language.Name == Loca.GetLanguageString(ELanguage.Russian))
                entry.StringContentRussian = text;
            else if (language.Name == Loca.GetLanguageString(ELanguage.Japanese))
                entry.StringContentJapanese = text;
            else if (language.Name == Loca.GetLanguageString(ELanguage.Chinese))
                entry.StringContentSimplifiedChinese = text;
            // Custom languages
            else if (CustomLanguages.TryGetKey(x => x.Value == language.Name, out ELanguage langId))
            {
                // Update text
                if (CustomLocalisations.TryGetKey(x => x.Value.Id == locaId, out string key))
                    CustomLocalisations[key].Data[langId] = text;
                // Add text
                else
                    CustomLocalisations.Add(original, new(locaId, new() { { langId, text } }));
            }
        }
    }

    /// <summary>
    /// Generate a JSON file which includes untranslated localisation data.<para/>
    /// This file can then easily be modified to add or edit language data.
    /// </summary>
    private static void GenerateTemplate()
    {
        // Only regenerate the template after updating to a new version
        //  or if it wasn't found
        if (GetTemplateVersion() == Application.version)
            return;

        Language lang = new() { Name = "English", GameVersion = Application.version };
        lang.Localisations.Add(-1, TemplateWarning);

        foreach (
            (
                string text,
                LocalisationData.LocalisationDataEntry loca
            ) in LocalisationData.Instance.LocaEntries.OrderBy(x => x.Value.ID)
        )
        {
            lang.Localisations.Add(loca.ID, text);
        }

        string json = JsonConvert.SerializeObject(lang, Formatting.Indented);
        Directory.CreateDirectory(LocalesPath);
        File.WriteAllText(Path.Join(LocalesPath, TemplateName), json);
    }

    /// <summary>
    /// Get the game version the current template file was created for.
    /// </summary>
    /// <returns>the game's version in semver format.</returns>
    private static string GetTemplateVersion()
    {
        try
        {
            string jsonTemplate = File.ReadAllText(Path.Join(LocalesPath, TemplateName));
            Language? lang = JsonConvert.DeserializeObject<Language>(jsonTemplate);

            return lang?.GameVersion ?? "0.0.0.0";
        }
        catch
        {
            return "0.0.0.0";
        }
    }
}
